package com.jonathan.chatoverhaul.event;

import com.mojang.logging.LogUtils;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.world.level.Level;
import org.slf4j.Logger;

/**
 * Single shared definition of the ARG Container duplicate dash-sound bug and
 * the one-line fix for it. Both DashSoundMixin (the Dash ability) and
 * LongJumpSoundMixin (the "Long Jump" / super-jump ability) delegate here, so
 * there is exactly one copy of the reasoning and one suppression point for
 * what is genuinely a single shared defect.
 *
 * THE ROOT CAUSE (traced from the_arg_container 0.4.3 bytecode):
 *
 * 1. Detection is a plain client keybind, in
 *    init.TheArgContainerModKeyMappings$DASH (KeyMapping#click / m_7249_):
 *
 *      if (isDownOld != isDown && isDown) {          // rising edge only
 *          PACKET_HANDLER.sendToServer(new DashMessage(0, 0));        // (a)
 *          DashMessage.pressAction(Minecraft.getInstance().player, 0, 0); // (b)
 *      }
 *      isDownOld = isDown;
 *
 *    Note it does BOTH (a) and (b): it tells the server, and it also runs the
 *    same action locally against the LocalPlayer. Line (b) is deliberate
 *    client-side prediction - DashProcedureProcedure.execute applies the
 *    velocity push and the food cost, so without (b) the dash would not feel
 *    responsive until the next position packet arrives. Removing (b) would
 *    break the ability, which is why this fix does not touch it.
 *
 * 2. The server side of (a) runs DashMessage#handler, which does
 *    context.getSender() -> enqueueWork -> pressAction -> the same
 *    DashProcedureProcedure.execute, but with a ServerLevel.
 *
 * 3. procedures.DashProcedureProcedure.execute
 *    (LLevelAccessor;DDDLEntity;)V then branches on level.isClientSide():
 *
 *      if (level instanceof Level) {
 *          if (level.isClientSide()) {
 *              Level.playSound(x, y, z, SOUND, NEUTRAL, vol, pitch, false);  // client
 *          } else {
 *              Level.playSound(null, BlockPos.containing(x, y, z), SOUND, NEUTRAL, vol, pitch); // server
 *          }
 *      }
 *
 *    The two branches are mutually exclusive, so neither one is "firing
 *    twice" on its own - and that is exactly why there is no error and no
 *    useful console output: from the server's point of view it plays the
 *    sound once, and from the client's point of view it plays the sound
 *    once. Nothing is duplicated within either side.
 *
 * 4. The duplication is across the two sides. The server branch passes a
 *    null Player, and vanilla's Level.playSound(@Nullable Player, ...) sends
 *    to every player in the level when that argument is null - including the
 *    player who just dashed. So on a dedicated server the dasher receives:
 *
 *      - one ClientboundSoundPacket generated by the server, and
 *      - one local Level.playSound from prediction step (b) above,
 *
 *    i.e. the same SoundEvent twice, ~1 RTT apart. That is the reported
 *    "plays twice". Other players nearby are unaffected - they only ever get
 *    the server broadcast - which matches the bug being reported from the
 *    dashing player's own perspective.
 *
 *    Singleplayer is affected by the identical mechanism, since the
 *    integrated server also broadcasts to the local ServerPlayer.
 *
 * THE FIX: drop the redundant client-side playback and let the server
 * broadcast remain the single source of truth. That keeps every behaviour
 * that matters:
 *
 *  - The velocity push, food cost and cooldown are all still applied by both
 *    the prediction call and the authoritative server call. Only the sound
 *    call is touched.
 *  - The sound still plays for everyone nearby, including the dasher, because
 *    the server already sends it to them.
 *  - The sound stays exactly where it belongs - driven by the server - so no
 *    client-only logic was moved to the server, and no other ARG Container
 *    sound is affected. Only the two sound call sites for these two
 *    abilities are redirected.
 *  - The dasher now hears it on the same timing as everyone else (~1 RTT)
 *    rather than instantly, which is consistent and imperceptible, instead
 *    of hearing a stuttered double.
 *
 * The alternative - keeping the local playback and excluding the dasher from
 * the server broadcast - is not achievable through the vanilla API:
 * Level.playSound(Player, ...) sends to that one player rather than to
 * everyone except them, so it cannot express "everyone but the dasher"
 * without rewriting ARG's broadcast loop by hand. Suppressing the redundant
 * half is both smaller and safer.
 */
public final class DashSoundCompat {

    private static final Logger LOGGER = LogUtils.getLogger();

    private static boolean reported;

    private DashSoundCompat() {
    }

    /**
     * Replaces ARG Container's client-local playback of the dash /
     * long-jump sound. Intentionally does nothing else.
     */
    public static void suppressDuplicateClientPlayback(Level level, SoundEvent sound) {
        if (!reported) {
            reported = true;
            LOGGER.info("[DLTCore] ARG Container duplicate dash-sound suppressed; "
                    + "server broadcast remains the single source of truth");
        }
    }
}